# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('shortcut', models.CharField(max_length=50)),
                ('default_value', models.FloatField(default=0)),
                ('scaling_factor', models.FloatField(default=1)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='shortcut',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='facultyindicators',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Faculty'),
        ),
        migrations.AddField(
            model_name='facultyindicators',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Indicator'),
        ),
    ]
