# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20160320_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='shortcut',
            field=models.CharField(max_length=50),
        ),
    ]
