# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20160320_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'permissions': (('view_faculty_indicators', 'Can see the list of indicators for a faculty'), ('edit_faculty_indicators', 'Can see and change the list of faculty indicators'))},
        ),
    ]
