# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20160322_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
    ]
