# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 17:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0006_auto_20160322_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyindicators',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='facultyindicators',
            name='ease_coefficient',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultyindicators',
            name='significance_coefficient',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultyindicators',
            name='time_interval_end',
            field=models.DateField(default=datetime.date.today, verbose_name='Interval end date'),
        ),
        migrations.AddField(
            model_name='facultyindicators',
            name='time_interval_start',
            field=models.DateField(default=datetime.date.today, verbose_name='Interval start date'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='given_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='university',
            name='total_rank',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='university_managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultyindicators',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.TextField(),
        ),
    ]