# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 13:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0006_auto_20160322_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorIntervals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Interval start date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='Interval end date')),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyindicators',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='facultyindicators',
            name='ease_coefficient',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultyindicators',
            name='significance_coefficient',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='given_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='university',
            name='total_rank',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='university_managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultyindicators',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='facultyindicators',
            name='time_interval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.IndicatorIntervals'),
            preserve_default=False,
        ),
    ]
