# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20160326_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date published'),
        ),
    ]