# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_auto_20160326_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorIntervals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Interval start date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='Interval end date')),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='facultyindicators',
            name='time_interval_end',
        ),
        migrations.RemoveField(
            model_name='facultyindicators',
            name='time_interval_start',
        ),
        migrations.AddField(
            model_name='facultyindicators',
            name='time_interval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.IndicatorIntervals'),
            preserve_default=False,
        ),
    ]
